language: Java
jdk:
  - oraclejdk8

before_script:
  - "npm install"
  - sleep 3

script:
  - cd ..
  - git clone https://github.com/axelhildingson/simple_react_test.git
  - cd simple_react_test
  - ./gradlew build
