language: Java
jdk:
  - oraclejdk8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - "npm install"
  - sleep 3

script:
  - cd public/scripts/
  - webpack ./main.js
  - cd ..
  - cd ..
  - ./start_server.sh
  - cd ..
  - git clone https://github.com/axelhildingson/simple_react_test.git
  - cd simple_react_test
  - ./gradlew test
